api = "0.2"

[buildpack]
id = "eddumelendez/lein-paketo-buildpack"
name = "Paketo Lein Buildpack"
version = "0.0.1"
homepage = "https://github.com/eddumelendez/lein-paketo-buildpack"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BP_LEIN_BUILD_ARGUMENTS"
description = "the arguments to pass to Maven"
default     = "uberjar"
build       = true

[[metadata.configurations]]
name        = "BP_LEIN_BUILT_ARTIFACT"
description = "the built application artifact explicitly.  Supersedes $BP_LEIN_BUILT_MODULE"
default     = "target/*-standalone.jar"
build       = true

[[metadata.configurations]]
name        = "BP_LEIN_BUILT_MODULE"
description = "the module to find application artifact in"
build       = true

[[metadata.dependencies]]
id      = "lein"
name    = "Leiningen"
version = "2.9.4"
uri     = "https://raw.githubusercontent.com/technomancy/leiningen/2.9.4/bin/lein"
sha256  = "1e21276bad56f4f8f8afd605ddf0c4d047a5244724a8dc6e13c6c55cc53b3fee"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
